-- AlterTable
ALTER TABLE `todo` ADD COLUMN `type` ENUM('RECENT', 'LONG_TERM', 'STUDY_PLAN') NOT NULL DEFAULT 'RECENT';

-- AlterTable
ALTER TABLE `user` MODIFY `password` VARCHAR(191) NOT NULL DEFAULT 123456,
    MODIFY `random` INTEGER NOT NULL DEFAULT 10;
